# Generated by Django 4.2.10 on 2024-02-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Job')),
                ('description', models.TextField(verbose_name='Description')),
                ('requirements', models.TextField(verbose_name='Requirements')),
                ('responsibilities', models.TextField(verbose_name='Responsibilities')),
                ('level', models.CharField(choices=[('jr', 'Júnior'), ('pl', 'Pleno'), ('sr', 'Sênior')], max_length=20, verbose_name='Level')),
                ('skills', models.ManyToManyField(to='jobs.skill', verbose_name='Skill')),
            ],
        ),
    ]
