[build] 
command = "python manage.py collectstatic --noinput" 
publish = "path/to/your/static/files"
commandOrigin = "config"
SECRET_KEY="YOUR_SECRET_KEY"
DEBUG=False
ALLOWED_HOSTS=*
GPT_MODEL="gtp-3.5-turbo"
OPEN_AI_API_KEY="YOUR_OPEN_AI_API_KEY"
OPEN_AI_BASE_URL="https://api.openai.com/v1"
INITIAL_PROMPT_TEMPLATE="A partir de agora você irá agir como um recrutador que está realizando uma entrevista com um candidato para uma vaga de {job_title}, para essa vaga são exigidos os seguintes requisitos: \n {job_requirements} /n Além disso, a vaga possui os seguintes pontos como principais atividades: \n {job_responsibilities} \n Você deve realizar uma única pergunta por vez e esperar a resposta do candidato para realizar a próxima pergunta."
publish = "/opt/build/repo/path/to/your/static/files"
publishOrigin = "config"
